# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 628bca1045abcc49d8a6e11d76c9ab654abaafd6f9a203ae2873c40b751150809e508d4a6ad155a062aa5a6c2e19819eb378a31aff51887b88d94f23dfccc403

test:
  secret_key_base: dbb575ee944b2bb6c071c4c772aef0f263d6002263ee7c49f829e3a79745275696b6574c49f5dcbd1647916789bfdfe1b10559d17b21c593341448d2a1a40012

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
